-- PROPUESTA DE CONSULTAS PARA MODELO DE FRAGMENTACION DEL SEGMENTO VENTAS

-- Listar el numero de ventas por territorio
-- Listar el numero de ventas por tienda 
-- Listar el total de clientes que pertenecen a cada territorio
-- Actualizar la oferta de llantas de monta�a con un descuento del 40%
-- Listar las ordenes realizadas debidas a anuncio de revista
-- Listar el total de ordenes hechas por cada representante de ventas
-- Agregar el producto "HL Road Frame - Black, 58" a la oferta "Descuento por volumen 11 a 14"
--La suma de total de venta por PersonID
--Tienda con mas ventas realizadas por tarjeta de credito